### ISSUE TITLE
bin/magento setup:di:compile command generates an error due to a "," left on a constructor

### ISSUE THREAD

**Issue by Rueff19** [Tun2U/M2-Module-VivaPayments#1]
When running the setup:di:compile command an error is given, because there is a "," at the end of the constructor for the Tun2U/VivaPayments/Controller/Multishipping/Start.php class.

Tun2U/VivaPayments/Controller/Multishipping/Start.php:39
<img width="614" alt="image" src="https://github.com/Tun2U/M2-Module-VivaPayments/assets/19212914/72ccf325-5baa-4319-b474-17d493dafbbf">

**Comment by GeorgeBortov** [comment]
@Rueff19 thank you for reporting this problem. I fixed this issue and made a new release.
